/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package celizationserver.swing;

import java.awt.Dimension;

/**
 *
 * @author mjafar
 */
public class MapPreview extends javax.swing.JDialog {

    /**
     * Creates new form MapPreview
     */
    public MapPreview(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension screenSize = celizationserver.core.ManagerStarter.screenSize;
        this.setLocation(screenSize.width - getWidth(), screenSize.height - getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPreview = new celizationserver.swing.PerlinNoisePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Preview");
        setAutoRequestFocus(false);
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlPreview.setToolTipText("");
        pnlPreview.setMaximumSize(null);
        pnlPreview.setName(""); // NOI18N

        javax.swing.GroupLayout pnlPreviewLayout = new javax.swing.GroupLayout(pnlPreview);
        pnlPreview.setLayout(pnlPreviewLayout);
        pnlPreviewLayout.setHorizontalGroup(
            pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        pnlPreviewLayout.setVerticalGroup(
            pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        getContentPane().add(pnlPreview, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public celizationserver.swing.PerlinNoisePanel pnlPreview;
    // End of variables declaration//GEN-END:variables
}
