/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package celizationserver.swing;

import celization.CElization;
import celization.GameState;
import celization.NaturalResources;
import celization.UserInfo;
import celizationserver.core.CElizationServer;
import celizationserver.core.Starter;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mjafar
 */
public class UserRegister extends javax.swing.JDialog {

    private boolean canceled = true;
    private InputVerifier usernameInputVerifier = new InputVerifier() {
        @Override
        public boolean verify(JComponent input) {
            JTextField t = (JTextField) input;
            t.setText(t.getText().trim());
            return t.getText().matches(celization.GameParameters.usernamePattern);
        }
    };
    private InputVerifier passwordInputVerifier = new InputVerifier() {
        @Override
        public boolean verify(JComponent input) {
            JTextField t = (JTextField) input;
            return (t.getText().length() >= 5 && t.getText().length() <= 25);
        }
    };

    /**
     * Creates new form UserRegister
     */
    public UserRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Starter.setCenter(this);
    }

    public void setGamesList(String[] list) {
        javax.swing.DefaultComboBoxModel<String> arrayModel;
        arrayModel = new javax.swing.DefaultComboBoxModel<>(list);
        lstGames.setModel(arrayModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGame = new javax.swing.JLabel();
        lstGames = new javax.swing.JComboBox();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        pnlInitialStatus = new javax.swing.JPanel();
        lblFoodDesc = new javax.swing.JLabel();
        lblLumberDesc = new javax.swing.JLabel();
        lblGold = new javax.swing.JLabel();
        lblStone = new javax.swing.JLabel();
        spnFood = new javax.swing.JSpinner();
        spnLumber = new javax.swing.JSpinner();
        spnGold = new javax.swing.JSpinner();
        spnStone = new javax.swing.JSpinner();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register new user");
        setModal(true);
        setResizable(false);

        lblGame.setText("Game:");

        lblUserName.setText("Username:");

        lblPassword.setText("Password:");

        txtUsername.setInputVerifier(usernameInputVerifier);

        txtPassword.setInputVerifier(passwordInputVerifier);

        pnlInitialStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("Initial Resources"));

        lblFoodDesc.setText("Food");

        lblLumberDesc.setText("Lumber");

        lblGold.setText("Gold");

        lblStone.setText("Stone");

        spnFood.setModel(new javax.swing.SpinnerNumberModel(50, 30, 200, 5));
        spnFood.setRequestFocusEnabled(false);

        spnLumber.setModel(new javax.swing.SpinnerNumberModel(50, 30, 200, 5));

        spnGold.setModel(new javax.swing.SpinnerNumberModel(50, 30, 200, 5));

        spnStone.setModel(new javax.swing.SpinnerNumberModel(50, 30, 200, 5));

        javax.swing.GroupLayout pnlInitialStatusLayout = new javax.swing.GroupLayout(pnlInitialStatus);
        pnlInitialStatus.setLayout(pnlInitialStatusLayout);
        pnlInitialStatusLayout.setHorizontalGroup(
            pnlInitialStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInitialStatusLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlInitialStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoodDesc)
                    .addComponent(lblLumberDesc))
                .addGap(70, 70, 70)
                .addGroup(pnlInitialStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnFood, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(spnLumber))
                .addGap(18, 18, 18)
                .addGroup(pnlInitialStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGold, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(pnlInitialStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnGold, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(spnStone))
                .addContainerGap())
        );
        pnlInitialStatusLayout.setVerticalGroup(
            pnlInitialStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInitialStatusLayout.createSequentialGroup()
                .addGroup(pnlInitialStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFoodDesc)
                    .addComponent(spnFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGold)
                    .addComponent(spnGold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInitialStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLumberDesc)
                    .addComponent(spnLumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStone)
                    .addComponent(spnStone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSave.setText("Register");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInitialStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGame)
                            .addComponent(lblUserName)
                            .addComponent(lblPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lstGames, 0, 240, Short.MAX_VALUE)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGame)
                    .addComponent(lstGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlInitialStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!txtUsername.getInputVerifier().verify(txtUsername)) {
            txtUsername.requestFocus();
            JOptionPane.showMessageDialog(rootPane,
                    "Username is not valid.\n"
                    + "You may only use letters numbers and underscore.",
                    "Username is not valid",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!txtPassword.getInputVerifier().verify(txtPassword)) {
            txtPassword.requestFocus();
            JOptionPane.showMessageDialog(rootPane,
                    "Password is eighter too short or too long!.\n"
                    + "Any character is acceptable and encouraged to use complex ones.",
                    "Password is not valid",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        canceled = false;
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    public boolean isCancelled() {
        return canceled;
    }

    public UserInfo getUserInfo(CElizationServer server) {
        UserInfo info;
        info = new UserInfo(txtUsername.getText(), txtPassword.getText());

        CElization game = server.getGame(lstGames.getSelectedItem().toString()).getGame();
        GameState newGameState = new GameState(game, txtUsername.getText());

        info.setGameInstance(newGameState);

        return info;
    }

    public Integer getPort(CElizationServer server) {
        return server.getPort(lstGames.getSelectedItem().toString());
    }

    public NaturalResources getInitialNaturalResources() {
        return new NaturalResources(
                Integer.valueOf(spnGold.getValue().toString()),
                Integer.valueOf(spnStone.getValue().toString()),
                Integer.valueOf(spnLumber.getValue().toString()), Integer.valueOf(spnFood.getValue().toString()), 0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblFoodDesc;
    private javax.swing.JLabel lblGame;
    private javax.swing.JLabel lblGold;
    private javax.swing.JLabel lblLumberDesc;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStone;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JComboBox lstGames;
    private javax.swing.JPanel pnlInitialStatus;
    private javax.swing.JSpinner spnFood;
    private javax.swing.JSpinner spnGold;
    private javax.swing.JSpinner spnLumber;
    private javax.swing.JSpinner spnStone;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
